# Generated by Django 3.2.20 on 2023-08-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230823_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
