# Generated by Django 3.2.20 on 2023-08-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
