# Generated by Django 3.2.20 on 2023-08-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_session_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
