# Generated by Django 3.2.20 on 2023-08-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_paymentlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlink',
            name='url',
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='stripe_session_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
