# Generated by Django 3.2.20 on 2023-08-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20230823_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stripe_session_id',
        ),
    ]
